name: SkUniversal
version: 1.6
author: _Donut_
main: us._donut_.skuniversal.SkUniversal
depend: [Skript]
softdepend: [AdvancedBan, AdvancedSurvivalGames, Autorank, Bedwars, Cannons, ClearLag, CombatLog, GriefPrevention, Lockette, LockettePro, LWC, MinePacks, Parties, PlotSquared, PrisonMines, PvPLevels, Shopkeepers, SkyWars]
commands:
  skuniversal:
    description: The main SkUniversal command.
    usage: /skuniversal
    permission: skuniversal.info
    permission-message: You don't have permission to use this command!
permissions:
  skuniversal.info:
    description: Allows the use of /skuniversal
    default: op