name: SkUniversal
version: 1.0
author: _Donut_
main: us._donut_.skuniversal.SkUniversal
depend: [Skript]
softdepend: [AdvancedBan, AdvancedSurvivalGames, Autorank, Bedwars, ClearLag, CombatLog, Lockette, LockettePro, LWC, MinePacks, Parties, PvPLevels, Shopkeepers, SkyWars]